# Generated by Django 4.2.1 on 2023-08-07 07:06

import computedfields.resolver
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeOverTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_time', models.IntegerField(blank=True, null=True)),
                ('hrs', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('price_per_kg', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5)),
                ('price_for_ratio', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
            bases=(computedfields.resolver._ComputedFieldsModelBase, models.Model),
        ),
        migrations.CreateModel(
            name='CompositionName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composition_name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField()),
                ('rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalComponentName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinishedGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('primary_sales_channel', models.CharField(blank=True, max_length=20)),
                ('weight', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mould',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=50)),
                ('work_center', models.CharField(blank=True, max_length=50)),
                ('cavity_number', models.IntegerField(null=True)),
                ('maximum_capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('optimum_capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cycle_time', models.IntegerField(null=True)),
                ('fg_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cogs.finishedgood')),
            ],
        ),
        migrations.CreateModel(
            name='MouldName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SemiFinishedGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('weight', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('component_quantity', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('price_for_composition_per_kg', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('material_cost_per_unit', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('composition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cogs.composition')),
                ('fg_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cogs.finishedgood')),
            ],
            options={
                'abstract': False,
            },
            bases=(computedfields.resolver._ComputedFieldsModelBase, models.Model),
        ),
        migrations.CreateModel(
            name='SalesPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psc_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ws_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('markup', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('fg_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cogs.finishedgood')),
            ],
            options={
                'verbose_name': 'Sales Price',
            },
        ),
        migrations.CreateModel(
            name='RawMaterialLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_material_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('landing_cost_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('landed_cost_per_kg', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5)),
                ('cost_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('material_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cogs.rawmaterialcategory')),
            ],
            options={
                'abstract': False,
            },
            bases=(computedfields.resolver._ComputedFieldsModelBase, models.Model),
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('fg_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cogs.finishedgood')),
                ('raw_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cogs.rawmateriallineitem')),
                ('sfg_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cogs.semifinishedgood')),
            ],
        ),
        migrations.CreateModel(
            name='Print',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embossing', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('printing', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('labeling', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('foil', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('glue', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('shrink_wrap', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('woven_polybag', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('inner_bag', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('carton', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('strapping', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('kes_u', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5)),
                ('fg_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cogs.finishedgood')),
            ],
            options={
                'abstract': False,
            },
            bases=(computedfields.resolver._ComputedFieldsModelBase, models.Model),
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('mmts', models.CharField(blank=True, editable=False, max_length=50, null=True)),
                ('kwh', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('kes_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('kes_hr', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('ct', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('cavity', models.IntegerField(blank=True, editable=False, null=True)),
                ('u_h', models.IntegerField(blank=True, editable=False, null=True)),
                ('kes_u', models.DecimalField(blank=True, decimal_places=6, editable=False, max_digits=15, null=True)),
                ('kes_sfg', models.DecimalField(blank=True, decimal_places=6, editable=False, max_digits=15, null=True)),
                ('fg_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cogs.finishedgood')),
                ('mould', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cogs.mould')),
                ('sfg_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cogs.semifinishedgood')),
            ],
            options={
                'abstract': False,
            },
            bases=(computedfields.resolver._ComputedFieldsModelBase, models.Model),
        ),
        migrations.CreateModel(
            name='Packing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50)),
                ('unit', models.IntegerField(blank=True, null=True)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('fg_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cogs.finishedgood')),
            ],
        ),
        migrations.AddField(
            model_name='mould',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cogs.mouldname'),
        ),
        migrations.AddField(
            model_name='mould',
            name='sfg_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cogs.semifinishedgood'),
        ),
        migrations.CreateModel(
            name='Labour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.IntegerField(blank=True, null=True)),
                ('mac_fte', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('mmts', models.CharField(blank=True, editable=False, max_length=50, null=True)),
                ('fg_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cogs.finishedgood')),
                ('mould', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cogs.mould')),
                ('sfg_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cogs.semifinishedgood')),
            ],
            options={
                'abstract': False,
            },
            bases=(computedfields.resolver._ComputedFieldsModelBase, models.Model),
        ),
        migrations.CreateModel(
            name='Labeling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50)),
                ('unit', models.IntegerField(blank=True, null=True)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('fg_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cogs.finishedgood')),
                ('sfg_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cogs.semifinishedgood')),
            ],
        ),
        migrations.CreateModel(
            name='Foiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50)),
                ('unit', models.IntegerField(blank=True, null=True)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('fg_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cogs.finishedgood')),
                ('sfg_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cogs.semifinishedgood')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalComponentLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.DecimalField(blank=True, decimal_places=2, max_digits=50)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cogs.externalcomponentname')),
            ],
            options={
                'abstract': False,
            },
            bases=(computedfields.resolver._ComputedFieldsModelBase, models.Model),
        ),
        migrations.CreateModel(
            name='ExternalComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cogs.externalcomponentlineitem')),
                ('fg_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cogs.finishedgood')),
            ],
        ),
        migrations.AddField(
            model_name='composition',
            name='composition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cogs.compositionname'),
        ),
        migrations.AddField(
            model_name='composition',
            name='material_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cogs.rawmateriallineitem'),
        ),
        migrations.CreateModel(
            name='ChangeOver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.IntegerField(blank=True, null=True)),
                ('target', models.IntegerField(blank=True, default=1, null=True)),
                ('mmts', models.CharField(blank=True, editable=False, max_length=50, null=True)),
                ('ct', models.IntegerField(blank=True, editable=False, null=True)),
                ('cavity', models.IntegerField(blank=True, editable=False, null=True)),
                ('max_u_m', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('oc_hr', models.IntegerField(blank=True, editable=False, null=True)),
                ('changes', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=15, null=True)),
                ('hrs', models.DecimalField(blank=True, decimal_places=5, editable=False, max_digits=10, null=True)),
                ('kes_u', models.IntegerField(blank=True, editable=False, null=True)),
                ('change_over_time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cogs.changeovertime')),
                ('fg_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cogs.finishedgood')),
                ('mould', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cogs.mould')),
                ('sfg_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cogs.semifinishedgood')),
            ],
            options={
                'abstract': False,
            },
            bases=(computedfields.resolver._ComputedFieldsModelBase, models.Model),
        ),
    ]
