# Generated by Django 4.2.1 on 2023-08-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packing',
            name='description',
        ),
        migrations.AddField(
            model_name='packing',
            name='sa_label',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
