# Generated by Django 4.2.1 on 2023-08-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogs', '0003_packing_carton_packing_foils_packing_inner_bag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packing',
            name='cost_per_unit',
        ),
        migrations.RemoveField(
            model_name='packing',
            name='unit',
        ),
        migrations.AlterField(
            model_name='packing',
            name='kes_u',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
