# Generated by Django 4.2.1 on 2023-08-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogs', '0004_remove_packing_cost_per_unit_remove_packing_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeover',
            name='kes_u',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
