# Generated by Django 4.2.1 on 2023-08-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogs', '0005_alter_changeover_kes_u'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour',
            name='kes_hr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='labour',
            name='kes_u',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='labour',
            name='other',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='labour',
            name='other_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='labour',
            name='print',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='labour',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='labour',
            name='u_h',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
