# Generated by Django 4.2.1 on 2023-08-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogs', '0006_labour_kes_hr_labour_kes_u_labour_other_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterial',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='mould',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
