# Generated by Django 4.2.1 on 2023-07-27 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_person', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_branch', models.CharField(max_length=100)),
                ('kenpoly_product_name', models.CharField(max_length=100)),
                ('kenpoly_price', models.IntegerField(null=True)),
                ('competitor_name', models.CharField(max_length=100)),
                ('competitor_product_name', models.CharField(max_length=100)),
                ('competitor_price', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBranches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_app.customers')),
            ],
        ),
    ]
